# Generated by Django 3.2.10 on 2023-01-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('is_infected', models.BooleanField()),
                ('count_reports', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Survivor',
                'verbose_name_plural': 'Survivors',
            },
        ),
        migrations.CreateModel(
            name='Inventory_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survivor_id', models.IntegerField(blank=True, default=0, null=True)),
                ('items', models.IntegerField()),
                ('inventories', models.ManyToManyField(to='restApi.Inventory', verbose_name='Inventories')),
            ],
            options={
                'verbose_name': 'Inventory_Item',
                'verbose_name_plural': 'Inventories_Items',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='survivor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restApi.survivor', verbose_name='Survivor'),
        ),
    ]
